# Generated by Django 3.1.4 on 2020-12-05 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='own_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
