# Generated by Django 3.1.4 on 2020-12-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201205_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requestiong_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requesting_users', to='accounts.group'),
        ),
    ]
