# Generated by Django 3.1.4 on 2020-12-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_requestiong_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='requestiong_group',
            new_name='requesting_group',
        ),
    ]
