version: '3'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env.db
    expose:
      - "5432"
  python:
    image: etmula/houseworkmanager:latest
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    image: etmula/django-nginx
    ports:
      - "8000:8000"
    depends_on:
      - python
