# Generated by Django 2.2.8 on 2020-11-30 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='accounts.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('point', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('alert', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='work.Category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='accounts.Group')),
            ],
        ),
        migrations.CreateModel(
            name='WorkUpdatedRecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('point', models.IntegerField(default=0)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_updated_recodes', to='work.Work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExectedRecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exected_date', models.DateField(default=django.utils.timezone.localdate)),
                ('name', models.CharField(max_length=30)),
                ('point', models.IntegerField(default=0)),
                ('executers', models.ManyToManyField(related_name='work_exected_recodes', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_exected_recodes', to='accounts.Group')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_exected_recodes', to='work.Work')),
            ],
        ),
    ]
