# Generated by Django 2.2.8 on 2020-11-30 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workupdatedrecode',
            name='created_at',
        ),
        migrations.AddField(
            model_name='work',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workupdatedrecode',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='workexectedrecode',
            name='executers',
            field=models.ManyToManyField(related_name='workexectedrecodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workexectedrecode',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workexectedrecodes', to='accounts.Group'),
        ),
        migrations.AlterField(
            model_name='workexectedrecode',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workexectedrecodes', to='work.Work'),
        ),
        migrations.AlterField(
            model_name='workupdatedrecode',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workupdatedrecodes', to='work.Work'),
        ),
    ]
