# Generated by Django 2.2.8 on 2020-11-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20201201_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workupdatedrecode',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
