# Generated by Django 2.2.8 on 2020-12-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20201202_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composite',
            old_name='parrent',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='parrent',
            new_name='parent',
        ),
    ]
