# Generated by Django 2.2.8 on 2020-12-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20201202_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composite',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composites', to='work.Composite'),
        ),
        migrations.AlterField(
            model_name='work',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='work.Composite'),
        ),
        migrations.AlterField(
            model_name='workexectedrecode',
            name='exected_date',
            field=models.DateField(),
        ),
    ]
