version: '3'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env.db
    expose:
      - "5432"
  python:
    build:
      context: ..
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/code
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - python
